### data
train_dataset_type: messages
eval_dataset_type: messages
train_dataset_path: ./data/formula_organic_ability_v7_counting_curriculum/combo_layout/sft/train.jsonl
train_dataset_prob: "1.0"
eval_dataset_path: ./data/formula_organic_ability_v7_counting_curriculum/combo_layout/sft/eval.jsonl
eval_dataset_prob: "1.0"
max_seq_len: 4096
padding_free: true
truncate_packing: false
dataloader_num_workers: 0
mix_strategy: concat
template_backend: custom
template: paddleocr_vl_v15
custom_register_path: ./configs/paddleocr_vl_v15_template.py

### model
model_name_or_path: ${BASE_MODEL_PATH}
_attn_implementation: flashmask
lora: true
lora_rank: 16
lora_path: ./outputs/paddleocr_vl15_formula_organic_ability_v6_hard_formula_lora_r16_b3ga2_round7_lr3e7
copy_custom_file_list: "configuration_paddleocr_vl.py image_processing_paddleocr_vl.py modeling_paddleocr_vl.py processing_paddleocr_vl.py inference.yml"

### finetuning
stage: VL-SFT
fine_tuning: lora
seed: 37
do_train: true
do_eval: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 3
num_train_epochs: 1
max_steps: -1
max_estimate_samples: 1600
eval_steps: 800
evaluation_strategy: steps
save_steps: 800
save_strategy: steps
logging_steps: 10
gradient_accumulation_steps: 2
logging_dir: ./outputs/paddleocr_vl15_formula_organic_ability_v7_counting_layout_lora_r16_b3ga2_round11_lr8e8/visualdl_logs
output_dir: ./outputs/paddleocr_vl15_formula_organic_ability_v7_counting_layout_lora_r16_b3ga2_round11_lr8e8
disable_tqdm: true
eval_accumulation_steps: 1

### train
lr_scheduler_type: cosine
warmup_ratio: 0.03
learning_rate: 8.0e-8
min_lr: 8.0e-9

### optimizer
weight_decay: 0.03
adam_epsilon: 1.0e-8
adam_beta1: 0.9
adam_beta2: 0.95

### performance
tensor_model_parallel_size: 1
pipeline_model_parallel_size: 1
sharding: stage1
recompute_granularity: full
recompute_method: uniform
recompute_num_layers: 1
bf16: true
fp16_opt_level: O2
pre_alloc_memory: 20

### save
unified_checkpoint: false
save_checkpoint_format: "flex_checkpoint"
load_checkpoint_format: "flex_checkpoint"

