### data
train_dataset_type: messages
eval_dataset_type: messages
train_dataset_path: /mnt/d/百度ocr比赛/output/formula_multiblock_v3/sft/smoke_train.jsonl
train_dataset_prob: "1.0"
eval_dataset_path: /mnt/d/百度ocr比赛/output/formula_multiblock_v3/sft/smoke_eval.jsonl
eval_dataset_prob: "1.0"
max_seq_len: 4096
padding_free: true
truncate_packing: false
dataloader_num_workers: 0
mix_strategy: concat
template_backend: custom
template: paddleocr_vl_v15
custom_register_path: /mnt/d/百度ocr比赛/train_configs/paddleocr_vl_v15_template.py

### model
model_name_or_path: PaddlePaddle/PaddleOCR-VL-1.5
_attn_implementation: flashmask
lora: true
lora_rank: 16
lora_path: /mnt/d/百度ocr比赛/output/paddleocr_vl15_formula_curriculum_v2_counts_lora_r16_b2ga8_2epoch
copy_custom_file_list: "configuration_paddleocr_vl.py image_processing_paddleocr_vl.py modeling_paddleocr_vl.py processing_paddleocr_vl.py inference.yml"

### finetuning
stage: VL-SFT
fine_tuning: lora
seed: 29
do_train: true
do_eval: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
num_train_epochs: 1
max_steps: 2
max_estimate_samples: 8
eval_steps: 1
evaluation_strategy: steps
save_steps: 2
save_strategy: steps
logging_steps: 1
gradient_accumulation_steps: 1
logging_dir: /mnt/d/百度ocr比赛/output/paddleocr_vl15_formula_multiblock_v3_lora_r16_b2ga8_smoke/visualdl_logs
output_dir: /mnt/d/百度ocr比赛/output/paddleocr_vl15_formula_multiblock_v3_lora_r16_b2ga8_smoke
disable_tqdm: true
eval_accumulation_steps: 1

### train
lr_scheduler_type: cosine
warmup_ratio: 0.03
learning_rate: 1.0e-5
min_lr: 1.0e-6

### optimizer
weight_decay: 0.03
adam_epsilon: 1.0e-8
adam_beta1: 0.9
adam_beta2: 0.95

### performance
tensor_model_parallel_size: 1
pipeline_model_parallel_size: 1
sharding: stage1
recompute_granularity: full
recompute_method: uniform
recompute_num_layers: 1
bf16: true
fp16_opt_level: O2
pre_alloc_memory: 20

### save
unified_checkpoint: false
save_checkpoint_format: "flex_checkpoint"
load_checkpoint_format: "flex_checkpoint"

